services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ignis
      POSTGRES_PASSWORD: ignis
      POSTGRES_DB: ignis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ignis"]
      interval: 5s
      timeout: 30s
      retries: 5
  redis:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend
    ports:
      - "8000:80"
    env_file: ./backend/.env
    volumes:
      - job_data:/data/jobs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  worker:
    build:  ./backend
    command: celery -A app.worker.celery_app worker --loglevel=info --concurrency=2
    env_file: ./backend/.env
    volumes:
      - job_data:/data/jobs
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
volumes:
  postgres_data:
  redis_data:
  job_data:
