"""create jobs table

Revision ID: 9d71f5be124b
Revises: 
Create Date: 2026-07-13 17:26:32.637011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d71f5be124b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'building', 'running', 'completed', 'failed', 'cancelled', name='jobstatus'), nullable=False),
    sa.Column('source_type', sa.Enum('zip', 'git', name='sourcetype'), nullable=False),
    sa.Column('git_url', sa.Text(), nullable=True),
    sa.Column('git_branch', sa.String(length=255), nullable=True),
    sa.Column('workspace_path', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('entrypoint', sa.Text(), nullable=False),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeout_minutes', sa.Integer(), nullable=True),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('artifacts_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
